In [23]:
import numpy as np

In [25]:
# single dimension
a = np.array([1,2,3,4,5])
print(a, type(a), a[1], a[1:], a[:-2])

[1 2 3 4 5] <class 'numpy.ndarray'> 2 [2 3 4 5] [1 2 3]


In [27]:
# multi dimension arrays
a_mul = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a_mul, a_mul[0], a_mul[0, 1], a_mul.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [1 2 3] 2 (3, 3)


In [61]:
# data types
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a.dtype)

b = np.array([[1,2,3], [4,"Hello",6], [7,8,9]])
print(b.dtype, b[0][0].dtype)

c = np.array([[1,2,3], [4,"5",6], [7,8,9]], dtype=np.int32)
print(c.dtype, c[1][1].dtype)

d = { 1 : "A" }
e = np.array([[1,2,3], [4,d,6], [7,8,9]])
print(e.dtype, type(e[0][0]))

int32
<U11 <U1
int32 int32
object <class 'int'>


In [83]:
# Filling Arrays
a = np.full((2,3,4), 9)
print(a)
print()

b = np.zeros((2,3))
print(b)
print()

c = np.ones((2,3))
print(c)
print()

d = np.empty((2,3))
print(d)
print()

# printing some sequence of number - arange(start, stop, step)
x_values = np.arange(0, 10, 1)
print(x_values)
print()

# printing sequence of numbers by splitting equally based on the num we give - linspace(start, space, count)
y_values = np.linspace(0, 10, 3)
print(y_values)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[0 1 2 3 4 5 6 7 8 9]

[ 0.  5. 10.]


In [85]:
# other properties

print(np.nan, np.inf)

nan inf


In [89]:
# mathematical operations

l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 = np.array(l1)
a2 = np.array(l2)

print(a1 * 5)
print(l1 * 5)

print(np.sqrt(a1))

[ 5 10 15 20 25]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [102]:
# Array Methods

a = np.array([1,2,3])
print(np.append(a, [4,5,6]), a)
print()
a = np.append(a, [4,5,6])

a = np.insert(a, 6, [7,8,9])
print(a)

print(np.delete(a, 8))

[1 2 3 4 5 6] [1 2 3]

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8]


In [126]:
# structuring methods
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a.reshape(2,6))
print()
print(a)
print()

a.resize((2,6))
print(a)
print()

# Flatten - To get the one dimensional array as output, returns the copy of the array
var1 = a.flatten()
var1[2] = 20
print(var1)
print()
print(a)
print()

# Ravel - Same like the flatten method but while returning it will give original array at that instance of time
var2 = a.ravel()
var2[2] = 20
print(var2)
print()
print(a)
print()

# To swap axis
print(a.transpose())
print()
print(a.T)
print()
print(a.swapaxes(0,1))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[ 1  2 20  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[ 1  2 20  4  5  6  7  8  9 10 11 12]

[[ 1  2 20  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  7]
 [ 2  8]
 [20  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]

[[ 1  7]
 [ 2  8]
 [20  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]

[[ 1  7]
 [ 2  8]
 [20  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [188]:
# concatinating, splitting, stacking
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
b = np.array([[11,12,13,14,15],
             [16,17,18,19,20]])
print(np.concatenate((a,b), axis=0))
print()
print(np.concatenate((a,b), axis=1))
print()

c = np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [10,11,12]])
print(np.split(c, 2, axis=0))
print()

d = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18],
              [19,20,21,22,23,24]])
print(np.split(d, 2, axis=1))

# stack is used for creating a outer list over a predefined list
# vstack act as same like the concatenate axis=0 concept
# hstack act as same like the concatenate axis=1 concept

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]

[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]


In [192]:
# aggregate functions
a = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18],
              [19,20,21,22,23,24]])
print(a.min())
print(a.max())
print(a.std())
print(a.sum())
print(np.median(a))

1
24
6.922186552431729
300
12.5


In [205]:
# Numpy Random
print(np.random.randint(100))
print()
print(np.random.randint(10, size=(2,3)))
print()
print(np.random.randint(90, 100, size=(2,3)))
print()
print(np.random.choice([10,20,30,40,50]))

90

[[6 2 7]
 [0 8 6]]

[[90 91 97]
 [95 98 92]]

30
